(dp1
S'output'
p2
S'Unable to open included view file: /Applications/web2py.app/Contents/Resources/applications/myapp/views/../layout.html'
p3
sS'layer'
p4
S'ParserContainer'
p5
sS'code'
p6
S'{{left_sidebar_enable=false}}\n{{extend \'../layout.html\'}}\n\n\n  <div id="logo"><img src="images/logo.png" width="227" height="71"></div>\n\n<div id="box">\n  <div id="content">\n    <div id="box_left"><img src="images/dashboard.jpg" width="348" height="296"></div>\n    \n    <div id="box_right">\n      <h1>Login</h1>\n      <div id="login"> Or insert your account informations: <br>\n        <form name="login" action="index.html" method="GET" accept-charset="utf-8">\n          <input type="text" placeholder="Username" id="l_user" class="login user" title="Username" required>\n          <input type="password" name="password" placeholder="Password" id="l_password" class="login password" title="Password" required>\n          \n          <br>\n          <input type="submit" value="Login" class="btn_login">\n        </form>\n      </div>\n      <div id="bottom_text"></div>\n    </div>\n  </div>\n</div>\n<div class="footer">&copy; 2014 Cynopsis -  <a href="#" id="contact" title="Contact">Contact</a> </div>\n'
p7
sS'snapshot'
p8
(dp9
S'exception'
p10
(dp11
S'__getslice__'
p12
S"<method-wrapper '__getslice__' of exceptions.IOError object>"
p13
sS'__str__'
p14
S"<method-wrapper '__str__' of exceptions.IOError object>"
p15
sS'__reduce__'
p16
S'<built-in method __reduce__ of exceptions.IOError object>'
p17
sS'__dict__'
p18
S'{}'
p19
sS'__sizeof__'
p20
S'<built-in method __sizeof__ of exceptions.IOError object>'
p21
sS'__init__'
p22
S"<method-wrapper '__init__' of exceptions.IOError object>"
p23
sS'__setattr__'
p24
S"<method-wrapper '__setattr__' of exceptions.IOError object>"
p25
sS'__reduce_ex__'
p26
S'<built-in method __reduce_ex__ of exceptions.IOError object>'
p27
sS'__new__'
p28
S'<built-in method __new__ of type object>'
p29
sS'errno'
p30
S'2'
sS'__format__'
p31
S'<built-in method __format__ of exceptions.IOError object>'
p32
sS'__class__'
p33
S"<type 'exceptions.IOError'>"
p34
sS'filename'
p35
S"'/Applications/web2py.app/Contents/Resources/applications/myapp/views/../layout.html'"
p36
sS'__doc__'
p37
S"'I/O operation failed.'"
p38
sS'__getitem__'
p39
S"<method-wrapper '__getitem__' of exceptions.IOError object>"
p40
sS'__setstate__'
p41
S'<built-in method __setstate__ of exceptions.IOError object>'
p42
sS'__getattribute__'
p43
S"<method-wrapper '__getattribute__' of exceptions.IOError object>"
p44
sS'args'
p45
S"(2, 'No such file or directory')"
p46
sS'__subclasshook__'
p47
S'<built-in method __subclasshook__ of type object>'
p48
sS'__unicode__'
p49
S'<built-in method __unicode__ of exceptions.IOError object>'
p50
sS'strerror'
p51
S"'No such file or directory'"
p52
sS'__delattr__'
p53
S"<method-wrapper '__delattr__' of exceptions.IOError object>"
p54
sS'__repr__'
p55
S"<method-wrapper '__repr__' of exceptions.IOError object>"
p56
sS'__hash__'
p57
S"<method-wrapper '__hash__' of exceptions.IOError object>"
p58
ssS'evalue'
p59
S"[Errno 2] No such file or directory: '/Applications/web2py.app/Contents/Resources/applications/myapp/views/../layout.html'"
p60
sS'frames'
p61
(lp62
(dp63
S'file'
p64
S'/Applications/web2py.app/Contents/Resources/gluon/template.py'
p65
sS'dump'
p66
(dp67
sS'lnum'
p68
I450
sS'lines'
p69
(dp70
I448
S'        # try to read the text.'
p71
sI449
S'        try:'
p72
sI450
S"            fileobj = open(filepath, 'rb')"
p73
sI451
S'            text = fileobj.read()'
p74
sI452
S'            fileobj.close()'
p75
sI453
S'        except IOError:'
p76
sI454
S"            self._raise_error('Unable to open included view file: ' + filepath)"
p77
sI445
S'        # Get the path of the file on the system.'
p78
sI446
S'        filepath = self.path and os.path.join(self.path, filename) or filename'
p79
sI447
S''
ssS'call'
p80
S"(self=<gluon.template.TemplateParser object>, filename='../layout.html')"
p81
sS'func'
p82
S'_get_file_text'
p83
sasS'pyver'
p84
S'Python 2.7.3: /Applications/web2py.app/Contents/MacOS/python (prefix: /Applications/web2py.app/Contents/Resources)'
p85
sS'etype'
p86
S"<type 'exceptions.IOError'>"
p87
sS'date'
p88
S'Fri Nov  7 12:43:09 2014'
p89
sS'locals'
p90
(dp91
S'self'
p92
S'<gluon.template.TemplateParser object>'
p93
sS'filepath'
p94
S"'/Applications/web2py.app/Contents/Resources/applications/myapp/views/../layout.html'"
p95
sS'context'
p96
S"{'A': <class 'gluon.html.A'>, 'ANY_OF': <class 'gluon.validators.ANY_OF'>, 'ASSIGNJS': <function ASSIGNJS>, 'Auth': <class 'gluon.tools.Auth'>, 'B': <class 'gluon.html.B'>, 'BEAUTIFY': <class 'gluon.html.BEAUTIFY'>, 'BODY': <class 'gluon.html.BODY'>, 'BR': <class 'gluon.html.BR'>, 'BUTTON': <class 'gluon.html.BUTTON'>, 'CAT': <class 'gluon.html.CAT'>, ...}"
p97
sg35
S"'../layout.html'"
p98
sssS'traceback'
p99
S'Traceback (most recent call last):\n  File "/Applications/web2py.app/Contents/Resources/gluon/template.py", line 450, in _get_file_text\nIOError: [Errno 2] No such file or directory: \'/Applications/web2py.app/Contents/Resources/applications/myapp/views/../layout.html\'\n'
p100
s.